# Generated by Django 5.2.9 on 2025-12-25 06:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_role', models.CharField(choices=[('Muội muội', 'Muội muội'), ('Sư huynh', 'Sư huynh'), ('Đệ đệ', 'Đệ đệ'), ('Tỷ tỷ', 'Tỷ tỷ')], max_length=20)),
                ('agent_role', models.CharField(choices=[('Tỷ tỷ', 'Tỷ tỷ'), ('Muội muội', 'Muội muội'), ('Tỷ tỷ ác ma', 'Tỷ tỷ ác ma')], max_length=20)),
                ('emotional_state', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(choices=[('user', 'User'), ('agent', 'Agent')], max_length=10)),
                ('content_raw', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='xiaoyue.chatsession')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_role', models.CharField(choices=[('Muội muội', 'Muội muội'), ('Sư huynh', 'Sư huynh'), ('Đệ đệ', 'Đệ đệ'), ('Tỷ tỷ', 'Tỷ tỷ')], default='Muội muội', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
